"use strict";
const $ = id => document.getElementById(id);
const state = {boot:null, history:[], result:null, view:"raw", source:"dataset", job:null, files:[], filtered:[]};
const alarmNames = {candidate:"候选异常", pending:"待连续确认", triggered:"告警触发", active:"告警中", interrupted:"告警中 · 观测中断", cleared:"已解除", idle:"未触发", unknown:"无法判定"};
const sourceNames = {historical_features:"历史特征分类", image_pipeline:"图像完整推理", unavailable:"分类暂不可用"};
const pageNames = {overview:["监控总览","让河道变化，清晰可见。","从河体分割到变化分析，追踪每一次观测。"],analysis:["对比分析","每一次变化，都有迹可循。","对照前后河体边界，查看分区几何变化。"],history:["检测与告警记录","留存观测，回溯依据。","查看本机检测结果、候选异常和连续告警记录。"],settings:["系统设置","为每次观测，设定尺度。","管理告警参数，查看当前模型与运行状态。"]};
function el(tag, cls, text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function toast(message){$("toast").textContent=message;$("toast").hidden=false;}
function clearToast(){$("toast").hidden=true;}
async function api(path,body){const response=await fetch(path,{method:body===undefined?"GET":"POST",headers:body===undefined?{}:{"Content-Type":"application/json","X-Monitor-Token":state.boot.token},body:body===undefined?undefined:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error||"请求失败");return data;}
function timeLabel(t){return t?t.replace("T"," ").slice(0,19):"—";}
function prediction(r){return r.prediction===null?"无法判定":r.prediction===1?"疑似堵塞":"未发现堵塞";}
function badgeClass(r){return r.prediction===null?"neutral":r.prediction===1?"positive":"normal";}
function percent(x){return Number.isFinite(x)?(x*100).toFixed(2)+"%":"—";}
function showPage(name){for(const node of document.querySelectorAll(".page"))node.hidden=node.id!=="page-"+name;for(const node of document.querySelectorAll(".nav"))node.classList.toggle("active",node.dataset.page===name);const p=pageNames[name];$("breadcrumb").textContent=p[0];$("page-title").textContent=p[1];$("page-subtitle").textContent=p[2];window.scrollTo(0,0);}
for(const node of document.querySelectorAll(".nav"))node.addEventListener("click",()=>showPage(node.dataset.page));
$("all-records").onclick=()=>showPage("history");
function selectedPair(){return state.filtered.find(p=>p.id===$("pair-select").value);}
function updatePairs(){if(!state.boot)return;state.filtered=state.boot.pairs.filter(p=>p.mode===$("mode").value&&(!$("legacy-only").checked||p.legacy_available));$("pair-select").replaceChildren(...state.filtered.map(p=>{const o=el("option",null,p.name+" · "+p.timestamp.slice(11,16)+(p.legacy_available?" · 可分类":""));o.value=p.id;return o;}));$("pair-count").textContent=state.filtered.length+" 对";previewPair();}
function previewPair(){const p=selectedPair();if(!p){$("pair-meta").textContent="没有符合条件的图像对";return;}$("pair-meta").textContent=timeLabel(p.timestamp_a)+" →\n"+timeLabel(p.timestamp)+"\n"+(p.legacy_available?"有配套历史特征，可运行旧分类器":"可运行分割与变化分析");if(!state.job&&state.source==="dataset"){state.view="raw";renderImage(p);if(state.result&&p.id!==state.result.id){$("assessment-description").textContent="以下为上次检测（"+timeLabel(state.result.timestamp)+"）的结果。当前所选图像对尚未分析。";$("assessment-badge").textContent="上次检测结果";}}}
function renderImage(pair){const p=pair||state.result;const result=state.result;const image=$("main-image");let src=null;
 if(state.view==="raw"&&p)src="/api/image/"+p.current;
 else if(result)src="/results/"+result.result_id+"/"+(state.view==="change"?"change.jpg":"current.jpg");
 image.hidden=!src;$("viewer-placeholder").hidden=!!src;if(src)image.src=src;
 $("viewer-label").textContent=p?timeLabel(p.timestamp):"等待观测数据";$("image-caption").textContent=p?p.name:"选择已有数据后可预览原图";$("image-mode").textContent=p?(p.mode==="day"?"白天观测":"夜间观测"):"—";
 for(const b of document.querySelectorAll("#view-tabs button"))b.classList.toggle("selected",b.dataset.view===state.view);
}
$("main-image").onerror=()=>{$("main-image").hidden=true;$("viewer-placeholder").hidden=false;$("image-caption").textContent="原图不可用，可切换到已保存的分割结果";};
for(const b of document.querySelectorAll("#view-tabs button"))b.onclick=()=>{if(b.dataset.view!=="raw"&&!state.result){toast("请先完成一次检测，再查看分割与变化区域。");return;}state.view=b.dataset.view;renderImage(state.result||selectedPair());};
$("mode").onchange=updatePairs;$("legacy-only").onchange=updatePairs;$("pair-select").onchange=previewPair;
function setSource(source){state.source=source;$("source-dataset").classList.toggle("selected",source==="dataset");$("source-upload").classList.toggle("selected",source==="upload");$("dataset-fields").hidden=source!=="dataset";$("upload-fields").hidden=source!=="upload";$("replay-button").hidden=source!=="dataset";$("input-help").textContent=source==="dataset"?"样本回放逐对独立检测，不代表连续视频流。":"上传图片使用当前分割模型；未配置配套分类器时显示无法判定。";}
$("source-dataset").onclick=()=>setSource("dataset");$("source-upload").onclick=()=>setSource("upload");
function busy(value){$("run-button").disabled=value;$("replay-button").disabled=value;$("stop-button").hidden=!value;$("mode").disabled=value;$("pair-select").disabled=value;$("stat-job").textContent=value?"分析中":"待命";}
async function refreshHistory(){state.history=await api("/api/history");renderHistory();}
function renderHistory(){const records=state.history;$("stat-runs").textContent=records.length;$("stat-alerts").textContent=records.filter(r=>r.prediction===1).length;
 $("recent-list").replaceChildren();for(const r of records.slice(0,3)){const row=el("button","recent-row");row.append(el("span","recent-icon",r.mode==="day"?"☀":"☾"));const text=el("div");text.append(el("b",null,timeLabel(r.timestamp)),el("small",null,sourceNames[r.source]));row.append(text,el("span","badge "+badgeClass(r),prediction(r)));row.onclick=()=>{renderResult(r);showPage("overview");};$("recent-list").append(row);}if(!records.length)$("recent-list").append(el("div","empty","还没有检测记录"));
 const filter=$("history-filter").value;const shown=records.filter(r=>filter==="all"||(filter==="positive"?r.prediction===1:r.prediction===null));$("history-body").replaceChildren();$("history-empty").hidden=shown.length>0;
 for(const r of shown){const tr=el("tr");tr.append(el("td",null,timeLabel(r.timestamp)),el("td",null,r.mode==="day"?"白天":"夜间"));const td=el("td");td.append(el("span","badge "+badgeClass(r),prediction(r)));tr.append(td,el("td",null,r.score===null?"—":r.score.toFixed(3)),el("td",null,sourceNames[r.source]),el("td",null,alarmNames[r.alarm]));const action=el("td");const button=el("button",null,"查看 ↗");button.onclick=()=>{renderResult(r);showPage("analysis");};action.append(button);tr.append(action);$("history-body").append(tr);}
}
$("history-filter").onchange=renderHistory;
function renderResult(r){state.result=r;state.view="overlay";renderImage();$("assessment-badge").className="badge "+badgeClass(r);$("assessment-badge").textContent=alarmNames[r.alarm];$("assessment-title").textContent=prediction(r);$("score").textContent=r.score===null?"—":r.score.toFixed(3);$("threshold").textContent="阈值 "+r.threshold.toFixed(2);$("area-current").textContent=percent(r.area_current);$("area-change").textContent=(r.area_change_pp>=0?"+":"")+r.area_change_pp.toFixed(2)+" pp";$("duration").textContent=r.seconds.toFixed(1)+" s";
 let explanation=r.source==="historical_features"?"使用此图像对的原始历史特征进行分类；当前分割仅用于展示与变化分析。该分数未经概率校准。":r.source==="image_pipeline"?"由当前图像分割、几何特征和配套分类器共同生成。":"";
 if(r.reasons.length)explanation+=" "+r.reasons.join("；");$("assessment-description").textContent=explanation;
 $("reference-time").textContent=timeLabel(r.timestamp_a);$("current-time").textContent=timeLabel(r.timestamp);
 for(const name of ["reference","current"]){$(name+"-image").src="/results/"+r.result_id+"/"+name+".jpg";$(name+"-image").hidden=false;}for(const n of document.querySelectorAll(".compare-empty"))n.hidden=true;
 const values=Array.from({length:20},(_,i)=>r.features["area_"+String(i).padStart(2,"0")]);const max=Math.max(.0001,...values.filter(Number.isFinite).map(Math.abs));$("geometry-chart").replaceChildren();values.forEach((v,i)=>{const col=el("div","bar-column");const bar=el("div","bar-stick "+(v>=0?"pos":"neg"));bar.style.height=(Number.isFinite(v)?Math.abs(v)/max*43:0)+"%";col.title="区域 "+(i+1)+"："+(Number.isFinite(v)?(v*100).toFixed(3)+" pp":"缺失");col.append(bar,el("small",null,String(i+1).padStart(2,"0")),el("span","bar-value",Number.isFinite(v)?(v*100).toFixed(1):"—"));$("geometry-chart").append(col);});
 $("provenance-text").textContent=sourceNames[r.source]+"。"+explanation+" 分割权重 SHA-256："+r.segmentation_sha256+(r.classifier_sha256?"；分类权重："+r.classifier_sha256:"")+(r.source_row?"；历史面积表行号："+r.source_row:"");
 $("downloads").replaceChildren();for(const [name,label]of [["reference_mask.png","下载参考 mask"],["current_mask.png","下载当前 mask"],["change.jpg","下载变化图"]]){const a=el("a",null,label+" ↗");a.href="/results/"+r.result_id+"/"+name;a.download=name;$("downloads").append(a);}
}
async function pollJob(){if(!state.job)return;try{const job=await api("/api/job?id="+state.job);$("job-progress").textContent=job.done+" / "+job.total+" · "+job.message;if(job.results.length){const last=job.results[job.results.length-1];if(!state.result||last.result_id!==state.result.result_id){renderResult(last);await refreshHistory();}}if(job.errors.length){$("task-errors").hidden=false;$("task-errors").textContent=job.errors.map(e=>(e.name||"任务")+"："+e.message).join("\n");}if(["complete","partial","failed","cancelled"].includes(job.status)){state.job=null;busy(false);$("stat-job").textContent=job.status==="failed"?"处理失败":job.status==="cancelled"?"已停止":"已完成";await refreshHistory();return;}setTimeout(pollJob,1200);}catch(e){toast(e.message+"；可刷新页面恢复任务状态。");busy(false);state.job=null;}}
async function startRun(replay=false){clearToast();$("task-errors").hidden=true;busy(true);try{let result;if(state.source==="dataset"){const pair=selectedPair();if(!pair)throw Error("请选择一个可用图像对");const start=state.filtered.indexOf(pair);const ids=(replay?state.filtered.slice(start,start+Number($("replay-count").value)):[pair]).map(p=>p.id);result=await api("/api/run",{pair_ids:ids});}else{if(state.files.length<2||state.files.length>20)throw Error("请选择 2–20 张图片");const files=[];for(let i=0;i<state.files.length;i++){const date=$("upload-time-"+i).value;if(!date)throw Error("请填写每张图片的拍摄时间");const file=state.files[i];const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(",")[1]);reader.onerror=()=>reject(Error("无法读取图片"));reader.readAsDataURL(file);});files.push({name:file.name,timestamp:date,data});}result=await api("/api/upload",{mode:$("mode").value,files});}state.job=result.job_id;pollJob();}catch(e){busy(false);toast(e.message);}}
$("run-button").onclick=()=>startRun(false);$("replay-button").onclick=()=>startRun(true);$("stop-button").onclick=async()=>{try{await api("/api/stop",{job_id:state.job});$("job-progress").textContent="正在停止，当前图像处理完成后结束";}catch(e){toast(e.message);}};
$("file-input").onchange=()=>{state.files=Array.from($("file-input").files);$("upload-list").replaceChildren();if(state.files.length>20){toast("一次最多上传 20 张图片");state.files=[];return;}for(let i=0;i<state.files.length;i++){const f=state.files[i],row=el("div","upload-item");row.append(el("span",null,(i+1)+". "+f.name));const t=el("input");t.type="datetime-local";t.step="1";t.id="upload-time-"+i;t.setAttribute("aria-label",f.name+" 的拍摄时间");const match=f.name.match(/(20\d{12})(?:\d{3})?/);if(match){const v=match[1];t.value=v.slice(0,4)+"-"+v.slice(4,6)+"-"+v.slice(6,8)+"T"+v.slice(8,10)+":"+v.slice(10,12)+":"+v.slice(12,14);}row.append(t);$("upload-list").append(row);}};
function fillSettings(){const a=state.boot.alert;$("setting-threshold").value=a.threshold;$("setting-clear").value=a.clear_threshold;$("setting-confirm").value=a.consecutive;$("setting-recover").value=a.clear_consecutive;$("setting-gap").value=a.max_gap_seconds;$("model-list").replaceChildren();for(const p of state.boot.profiles){const row=el("div","model-row");row.append(el("b",null,p.name),el("span","badge "+(p.ready?"normal":"positive"),p.ready?"权重就绪":"权重缺失"),el("p",null,p.checkpoint),el("p",null,p.classifier?"已配置图像分类器，推理时校验版本":"新图像分类器待配置；支持历史样本分类"));$("model-list").append(row);}const row=el("div","model-row");row.append(el("b",null,"历史双分支 CNN"),el("span","badge "+(state.boot.legacy_ready?"normal":"positive"),state.boot.legacy_ready?"权重就绪":"权重缺失"),el("p",null,state.boot.legacy_pairs+" 对图像匹配到原始历史特征"));$("model-list").append(row);}
$("settings-form").onsubmit=async event=>{event.preventDefault();try{state.boot.alert=await api("/api/settings",{threshold:Number($("setting-threshold").value),clear_threshold:Number($("setting-clear").value),consecutive:Number($("setting-confirm").value),clear_consecutive:Number($("setting-recover").value),max_gap_seconds:Number($("setting-gap").value)});toast("告警参数已保存，将用于后续任务。");}catch(e){toast(e.message);}};
function tick(){$("clock").textContent=new Date().toLocaleString("zh-CN",{hour12:false});}tick();setInterval(tick,1000);
async function init(){try{state.boot=await api("/api/bootstrap");$("connection").textContent="服务已连接";$("device").textContent=state.boot.device.toUpperCase()+" / LOCAL INFERENCE";$("stat-pairs").textContent=state.boot.pairs.length;updatePairs();fillSettings();await refreshHistory();if(state.boot.active_job){state.job=state.boot.active_job;busy(true);pollJob();}else if(state.history.length){renderResult(state.history[0]);}if(state.boot.legacy_issue)toast("历史特征索引："+state.boot.legacy_issue);}catch(e){$("connection").textContent="连接失败";toast(e.message);$("run-button").disabled=true;$("replay-button").disabled=true;}}init();
